import { PastDocumentItem, AuditSummaryMetrics, RiskCategoryScore, AgentChatMessage } from './types';

export const MOCK_METRICS: AuditSummaryMetrics = {
  totalAudits: 48,
  overallRiskScore: 24, // low risk percentage
  compliancePassRate: 86, // 86% compliance
  totalRedlines: 194,
  criticalFlags: 3,
};

export const MOCK_RISK_CATEGORIES: RiskCategoryScore[] = [
  { category: 'Limitation of Liability', score: 45, status: 'HIGH_RISK' },
  { category: 'Indemnification & Defense', score: 65, status: 'DEVIATION' },
  { category: 'Intellectual Property Rights', score: 92, status: 'COMPLIANT' },
  { category: 'Data Privacy & Confidentiality', score: 98, status: 'COMPLIANT' },
  { category: 'Termination & Remedies', score: 78, status: 'DEVIATION' },
  { category: 'Governing Law & Jurisdiction', score: 100, status: 'COMPLIANT' },
];

export const MOCK_PAST_DOCUMENTS: PastDocumentItem[] = [
  {
    id: 'doc-001',
    sessionId: 'session-acme-vendor-msa',
    contractName: 'Acme_Corp_Master_Services_Agreement_2026.docx',
    playbookName: 'Standard Vendor MSA Playbook v2.1',
    fileType: 'docx',
    uploadDate: '2026-08-25 14:30',
    clauseCount: 18,
    deviationsCount: 4,
    overallRisk: 'HIGH',
    status: 'AWAITING_HUMAN',
    criticScore: 94,
  },
  {
    id: 'doc-002',
    sessionId: 'session-cloudtech-saas',
    contractName: 'CloudTech_Enterprise_SaaS_License.docx',
    playbookName: 'Standard Software License Playbook',
    fileType: 'docx',
    uploadDate: '2026-08-24 11:15',
    clauseCount: 14,
    deviationsCount: 2,
    overallRisk: 'MEDIUM',
    status: 'COMPLETED',
    criticScore: 100,
  },
  {
    id: 'doc-003',
    sessionId: 'session-global-nda',
    contractName: 'Global_Logistics_Bilateral_NDA.pdf',
    playbookName: 'Universal Confidentiality Playbook',
    fileType: 'pdf',
    uploadDate: '2026-08-23 09:40',
    clauseCount: 9,
    deviationsCount: 0,
    overallRisk: 'LOW',
    status: 'COMPLETED',
    criticScore: 100,
  },
  {
    id: 'doc-004',
    sessionId: 'session-apex-subcontractor',
    contractName: 'Apex_Systems_Subcontractor_Agreement.docx',
    playbookName: 'Standard Vendor MSA Playbook v2.1',
    fileType: 'docx',
    uploadDate: '2026-08-22 16:50',
    clauseCount: 22,
    deviationsCount: 6,
    overallRisk: 'CRITICAL',
    status: 'AWAITING_HUMAN',
    criticScore: 88,
  },
  {
    id: 'doc-005',
    sessionId: 'session-horizon-dpa',
    contractName: 'Horizon_Health_Data_Processing_Addendum.pdf',
    playbookName: 'GDPR & HIPAA Compliance Playbook',
    fileType: 'pdf',
    uploadDate: '2026-08-20 13:10',
    clauseCount: 16,
    deviationsCount: 1,
    overallRisk: 'MEDIUM',
    status: 'COMPLETED',
    criticScore: 96,
  },
];

export const MOCK_AGENT_CHAT_LOGS: AgentChatMessage[] = [
  {
    id: 'msg-101',
    agentRole: 'Orchestrator',
    agentName: 'Orchestrator (Lead Counsel)',
    avatarColor: 'bg-purple-600',
    timestamp: '14:30:02',
    message: 'Session initialised. Starting document parsing and structure-aware clause tree extraction for "Acme_Corp_Master_Services_Agreement_2026.docx".',
  },
  {
    id: 'msg-102',
    agentRole: 'Auditor',
    agentName: 'Auditor Agent (Paralegal)',
    avatarColor: 'bg-blue-600',
    timestamp: '14:30:05',
    message: 'Extracted 18 structural clauses. Querying FastMCP playbook vector store for exact rule citations...',
  },
  {
    id: 'msg-103',
    agentRole: 'Auditor',
    agentName: 'Auditor Agent (Paralegal)',
    avatarColor: 'bg-blue-600',
    timestamp: '14:30:12',
    clauseId: 'clause_4_limitation_liability',
    citationId: 'RULE-LIMITATION-LIABILITY-01',
    message: 'Flagged Clause 4 (Limitation of Liability): Vendor attempts uncapped liability for indirect damages. Classification: DEVIATION (Severity: HIGH). Cited Rule: RULE-LIMITATION-LIABILITY-01.',
  },
  {
    id: 'msg-104',
    agentRole: 'Redliner',
    agentName: 'Redliner Agent (Drafter)',
    avatarColor: 'bg-emerald-600',
    timestamp: '14:30:15',
    clauseId: 'clause_4_limitation_liability',
    message: 'Formulated OOXML tracked-changes edit: Substituted uncapped clause with approved fallback language capping liability to 12 months of total fees paid under Agreement.',
  },
  {
    id: 'msg-105',
    agentRole: 'Critic',
    agentName: 'Critic Agent (Validator)',
    avatarColor: 'bg-amber-600',
    timestamp: '14:30:18',
    clauseId: 'clause_4_limitation_liability',
    message: 'Grounding Verification: Passed. Proposed edit is 100% grounded in RULE-LIMITATION-LIABILITY-01. Entailment score: 0.96.',
  },
  {
    id: 'msg-106',
    agentRole: 'Orchestrator',
    agentName: 'Orchestrator (Lead Counsel)',
    avatarColor: 'bg-purple-600',
    timestamp: '14:30:20',
    message: 'Transitioning session state to AWAITING_HUMAN. Interactive audit workspace ready for user review and approval.',
  },
];
